version: '3.9'

services:
  bot:
    container_name: bot
    hostname: bot
    build:
      context: ./bot
  logstash:
    container_name: logstash
    hostname: logstash
    build:
      context: ./logstash
    volumes:
      - ${PWD}/logstash/files/logstash.yml:/app/config/logstash.yml:ro
      - ${PWD}/logstash/files/pipelines.yml:/app/config/pipelines.yml:ro
      - ${PWD}/logstash/files/entrypoints/logstash.sh:/app/entrypoint.sh:ro
      - logstash-data:/app/config/pipelines:ro
      - build-data:/data:rw
  filters:
    container_name: filters
    hostname: filters
    build:
      context: ./logstash
    volumes:
      - ${PWD}/logstash/files/pipelines:/app/config/pipelines:ro
      - ${PWD}/logstash/files/entrypoints/logstash-filters.sh:/app/entrypoint.sh:ro
      - logstash-data:/data:rw
  build:
    container_name: build
    hostname: build
    build:
      context: ./build
    volumes:
      - ${PWD}/build/entrypoint.sh:/root/entrypoint.sh:ro
      - build-data:/root/data:rw
      - build-cache:/root/.gradle:rw

volumes:
  logstash-data:
  build-data:
  build-cache: