version: '3.9'

services:
  bot:
    build:
      context: ./bot
    deploy:
      replicas: 25
  logstash:
    container_name: logstash
    hostname: logstash
    ports:
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xmx8g -Xms8g -Dls.cgroup.cpuacct.path.override=/ -Dls.cgroup.cpu.path.override=/"
    build:
      context: ./logstash
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 9G
        reservations:
          cpus: '4'
          memory: 9G
    volumes:
      - ${PWD}/logstash/files/logstash.yml:/root/config/logstash.yml:ro
      - ${PWD}/logstash/files/pipelines.yml:/root/config/pipelines.yml:ro
      - ${PWD}/logstash/files/entrypoints/logstash.sh:/root/entrypoint.sh:ro
      - logstash-pipelines:/root/config/pipelines:ro
      - build-data:/plugins:rw
  pipelines:
    container_name: pipelines
    hostname: pipelines
    build:
      context: ./logstash
    volumes:
      - ${PWD}/logstash/files/pipelines:/root/config/pipelines:ro
      - ${PWD}/logstash/files/entrypoints/logstash-filters.sh:/root/entrypoint.sh:ro
      - logstash-pipelines:/pipelines:rw
  build:
    container_name: build
    hostname: build
    build:
      context: ./build
    volumes:
      - ${PWD}/build/entrypoint.sh:/root/entrypoint.sh:ro
      - build-data:/root/data:rw
      - build-cache:/root/.gradle:rw

volumes:
  logstash-pipelines:
  build-data:
  build-cache: