version: '3.9'

services:
  performance:
    deploy:
      replicas: 1
    build:
      context: ./performance
    environment:
      - "LINES=10000"
    volumes:
      - ${PWD}/performance/files/filebeat.yml:/app/filebeat.yml:ro
      - ${PWD}/performance/entrypoint.sh:/app/entrypoint.sh:ro
  bot:
    build:
      context: ./bot
    deploy:
      replicas: 1
  logstash:
    container_name: logstash
    hostname: logstash
    ports:
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xmx8g -Xms8g -Dls.cgroup.cpuacct.path.override=/ -Dls.cgroup.cpu.path.override=/"
      - "SAWMILL_PIPELINES_DIR=/root/config/pipelines/sawmill"
      - "SAWMILL_GEOIP_DB_DIR=/root/config/geoip"
    build:
      context: ./logstash
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 9G
        reservations:
          cpus: '4'
          memory: 9G
    volumes:
      - ${PWD}/logstash/files/GeoLite2-City.mmdb:/root/config/geoip/GeoLite2-City.mmdb:ro
      - ${PWD}/logstash/files/logstash.yml:/root/config/logstash.yml:ro
      - ${PWD}/logstash/files/pipelines.yml:/root/config/pipelines.yml:ro
      - ${PWD}/logstash/files/entrypoints/logstash.sh:/root/entrypoint.sh:ro
      - logstash-pipelines:/root/config/pipelines:ro
      - build-data:/plugins:rw
  pipelines:
    container_name: pipelines
    hostname: pipelines
    build:
      context: ./pipelines
    volumes:
      - ${PWD}/pipelines/files/pipelines:/pipelines/input:ro
      - ${PWD}/pipelines/entrypoint.sh:/root/entrypoint.sh:ro
      - logstash-pipelines:/pipelines/output:rw
  build:
    container_name: build
    hostname: build
    build:
      context: ./build
    volumes:
      - ${PWD}/build/entrypoint.sh:/root/entrypoint.sh:ro
      - build-data:/root/data:rw
      - build-cache:/root/.gradle:rw

volumes:
  logstash-pipelines:
  build-data:
  build-cache: