filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/server.log
    fields:
      type: json
      logzio_codec: json
    fields_under_root: true
    encoding: utf-8

output.logstash:
  hosts: [ "logstash:5044" ]
  loadbalance: true